// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS8MiYYk5WQufEOflI06d797KCoYQGNsU',
    appId: '1:1020213673968:web:ec21dda88dce372f62a735',
    messagingSenderId: '1020213673968',
    projectId: 'traveltribe-7ddea',
    authDomain: 'traveltribe-7ddea.firebaseapp.com',
    databaseURL: 'https://traveltribe-7ddea-default-rtdb.firebaseio.com',
    storageBucket: 'traveltribe-7ddea.firebasestorage.app',
    measurementId: 'G-FJ0595BZH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvAV94U9yvBLrz7O3Rhu7duV28TDMeTxI',
    appId: '1:1020213673968:android:577bf0b8a1414c4762a735',
    messagingSenderId: '1020213673968',
    projectId: 'traveltribe-7ddea',
    databaseURL: 'https://traveltribe-7ddea-default-rtdb.firebaseio.com',
    storageBucket: 'traveltribe-7ddea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB2X8PwBTR9n9_rP7-fGqGsTO0JurUA_0',
    appId: '1:1020213673968:ios:7ec6b955a21e570362a735',
    messagingSenderId: '1020213673968',
    projectId: 'traveltribe-7ddea',
    databaseURL: 'https://traveltribe-7ddea-default-rtdb.firebaseio.com',
    storageBucket: 'traveltribe-7ddea.firebasestorage.app',
    iosBundleId: 'com.example.traveltribe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB2X8PwBTR9n9_rP7-fGqGsTO0JurUA_0',
    appId: '1:1020213673968:ios:7ec6b955a21e570362a735',
    messagingSenderId: '1020213673968',
    projectId: 'traveltribe-7ddea',
    databaseURL: 'https://traveltribe-7ddea-default-rtdb.firebaseio.com',
    storageBucket: 'traveltribe-7ddea.firebasestorage.app',
    iosBundleId: 'com.example.traveltribe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS8MiYYk5WQufEOflI06d797KCoYQGNsU',
    appId: '1:1020213673968:web:be9400cc4af7649462a735',
    messagingSenderId: '1020213673968',
    projectId: 'traveltribe-7ddea',
    authDomain: 'traveltribe-7ddea.firebaseapp.com',
    databaseURL: 'https://traveltribe-7ddea-default-rtdb.firebaseio.com',
    storageBucket: 'traveltribe-7ddea.firebasestorage.app',
    measurementId: 'G-HDQ44ZPKJ3',
  );

}